# Generated by Django 5.2.3 on 2025-06-18 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCultura', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Propriedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomePropriedade', models.CharField(max_length=100)),
                ('localizacao', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Plantio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaPlantada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cultura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantio.cultura')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantio.propriedade')),
            ],
        ),
        migrations.CreateModel(
            name='Colheita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataColheita', models.DateField()),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plantio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantio.plantio')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeFuncionario', models.CharField(max_length=100)),
                ('funcao', models.CharField(max_length=50)),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantio.propriedade')),
            ],
        ),
        migrations.CreateModel(
            name='UsoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataUso', models.DateField()),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantio.insumo')),
                ('plantio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantio.plantio')),
            ],
            options={
                'unique_together': {('plantio', 'insumo', 'dataUso')},
            },
        ),
    ]
